option(CONFIG_STM32 "Enable STM32" OFF)
option(CONFIG_SDL2 "Enable SDL2" OFF)
option(CONFIG_LOGGING "Enable logging" ON)
if (CONFIG_LOGGING)
	set(CONFIG_LOGGING_LEVEL 4 CACHE STRING "Set log output level")
	option(CONFIG_LOGGING_LED "Use LED logging backend" OFF)
	option(CONFIG_LOGGING_USART "Use USART logging backed" ON)
	option(CONFIG_LOGGING_SEMIHOSTING "Use semihosting logging backed" OFF)
endif(CONFIG_LOGGING)

if (CONFIG_STM32)
	option(CONFIG_MIPI "Enable MIPI Interface" ON)
	option(CONFIG_LCD "Enabled LCD" ON)
endif(CONFIG_STM32)
