option(CONFIG_SDL2 "Enable SDL2" OFF)
option(CONFIG_LOGGING "Enable logging" OFF)
option(CONFIG_MIPI "Enable MIPI Interface" OFF)
option(CONFIG_LCD "Enabled LCD" OFF)
if (CONFIG_LOGGING)
	set(CONFIG_LOGGING_LEVEL 4 CACHE STRING "Set log output level")
	option(CONFIG_LOGGING_LED "Use LED logging backend" OFF)
	option(CONFIG_LOGGING_USART "Use USART logging backed" OFF)
	option(CONFIG_LOGGING_SEMIHOSTING "Use semihosting logging backed" OFF)
endif(CONFIG_LOGGING)

