# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Prepare build environment
      run: sudo apt install -y gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi libsdl2-dev ninja-build

    # Runs a set of commands using the runners shell
    - name: Build stmnes
      run: |
        cmake -B build/stm32 -G Ninja -DCMAKE_TOOLCHAIN_FILE=script/arm-none-eabi-toolchain.cmake
        cmake --build build/stm32
      
    - name: Build nesdl
      run: |
        cmake -B build/nesdl -G Ninja -DCONFIG_SDL2=ON
        cmake --build build/nesdl --target nesdl
